receivers = []
builtins = [
  "template.tag.block",
  "template.tag.include",
  "template.tag.extends",
  "template.tag.import",
  "template.tag.from",
  "template.tag.with",
  "template.tag.endwith",
  "template.tag.endblock",
  "template.tag.if",
  "template.tag.elif",
  "template.tag.else",
  "template.tag.endif",
  "template.tag.for",
  "template.tag.empty",
  "template.tag.endfor",
  "template.tag.macro",
  "template.tag.endmacro",
  "template.tag.set",
  "template.tag.autoescape",
  "template.tag.endautoescape",
  "template.tag.filter",
  "template.tag.endfilter",
  "template.tag.call",
  "template.tag.endcall",
  "template.tag.trans",
  "template.tag.endtrans",
  "template.tag.raw",
  "template.tag.endraw",
  "template.tag.endset",
]
filters = [
  "template.filter.default",
  "template.filter.date",
  "template.filter.length",
  "template.filter.escape",
  "template.filter.safe",
  "template.filter.upper",
  "template.filter.lower",
  "template.filter.urlencode",
  "template.filter.e",
  "template.filter.selectattr",
  "template.filter.list",
  "template.filter.first",
  "template.filter.last",
  "template.filter.join",
  "template.filter.tojson",
  "template.filter.int",
  "template.filter.float",
  "template.filter.round",
  "template.filter.sum",
]
routes = []
